# Generated by Django 4.0.10 on 2024-02-06 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_time', models.DateTimeField(auto_now_add=True, help_text='Time at 21.5 Rs')),
                ('longitude', models.FloatField(help_text='-180 degrees <= longitude cone axis <= 180 degrees, with 0 in the Earth direction ')),
                ('latitude', models.FloatField(help_text='-60 degrees <= Co-latitude cone axis <= + 60 degrees')),
                ('half_angle', models.FloatField(help_text=' 0 <= cone radius (half of the full angular width of the cone) <= 60 degrees')),
                ('speed', models.FloatField(help_text='0 <= Radial velocity <= 3000 km/s')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
