# Generated by Django 4.0.10 on 2024-02-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_cactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cactus',
            name='initial_time',
        ),
    ]
