# Generated by Django 4.0.10 on 2024-02-06 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0005_cactus_cme_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cactus',
            new_name='CME',
        ),
    ]
