# Generated by Django 4.0.10 on 2024-02-06 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_cactus_cme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cme',
            name='author',
        ),
    ]
