# Generated by Django 4.0.10 on 2024-02-06 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_cme_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='cme',
            name='issue_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
    ]
