# Generated by Django 4.0.10 on 2024-02-07 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_cme_issue_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flare_number', models.CharField(default='none', max_length=200)),
                ('issue_time', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0))),
                ('alert_text', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
