# Generated by Django 4.0.10 on 2024-02-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_flare'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magnetogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='magnetograms/')),
            ],
        ),
    ]
