# Generated by Django 4.0.10 on 2024-02-07 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_magnetogram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magnetogram',
            name='description',
        ),
        migrations.RemoveField(
            model_name='magnetogram',
            name='title',
        ),
        migrations.AddField(
            model_name='magnetogram',
            name='issue_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0)),
        ),
    ]
