# Generated by Django 4.0.10 on 2024-02-07 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_magnetogram_magnetogram_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulletin_number', models.CharField(default='none', max_length=200)),
                ('issue_time', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0))),
                ('solar_weather', models.CharField(default='none', max_length=3000)),
                ('geo', models.CharField(default='none', max_length=3000)),
            ],
        ),
    ]
