# Generated by Django 4.0.10 on 2024-02-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_bulletin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulletin',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=200),
        ),
        migrations.AddField(
            model_name='cme',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=200),
        ),
        migrations.AddField(
            model_name='flare',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=200),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
