# Generated by Django 4.0.10 on 2024-02-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_bulletin_comment_cme_comment_flare_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=400),
        ),
    ]
