# Generated by Django 4.0.10 on 2024-02-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_alter_flare_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='magnetogram',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=200),
        ),
    ]
