# Generated by Django 4.0.10 on 2024-02-15 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_magnetogram_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectrogram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spectrogram_number', models.CharField(default='none', max_length=200)),
                ('issue_time', models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0))),
                ('image', models.ImageField(upload_to='magnetograms/')),
                ('alert_text', models.CharField(default='none', max_length=200)),
            ],
        ),
    ]
