# Generated by Django 4.0.10 on 2024-02-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_spectrogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrogram',
            name='alert_text',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='image',
            field=models.ImageField(blank=True, upload_to='spectrograms/'),
        ),
    ]
