# Generated by Django 4.0.10 on 2024-02-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_alter_spectrogram_alert_text_alter_spectrogram_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrogram',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=200),
        ),
    ]
