# Generated by Django 4.0.10 on 2024-02-26 12:52

import datetime
from django.db import migrations, models
#from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_spectrogram_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flare',
            name='issue_time',
            field=models.DateTimeField(default=datetime.datetime(2012, 7, 12, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
