# Generated by Django 4.0.10 on 2024-02-26 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_cme_issue_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='issue_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='cme',
            name='initial_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), help_text='Time at 21.5 Rs'),
        ),
        migrations.AlterField(
            model_name='magnetogram',
            name='issue_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='issue_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
