# Generated by Django 4.0.10 on 2024-02-26 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0022_alter_bulletin_issue_time_alter_cme_initial_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cme',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=1000),
        ),
        migrations.AlterField(
            model_name='cme',
            name='issue_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='flare',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=1000),
        ),
        migrations.AlterField(
            model_name='magnetogram',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=1000),
        ),
        migrations.AlterField(
            model_name='spectrogram',
            name='comment',
            field=models.CharField(default='none', help_text='Source/reference', max_length=1000),
        ),
    ]
