# Generated by Django 5.0.4 on 2024-04-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_cme_comment_alter_cme_issue_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bulletin',
        ),
    ]
